Задание 1.3.1

Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и
единицами.

In [ ]:
import numpy as np

a = np.zeros((8, 8))
a[1::2, ::2] = 1
a[::2, 1::2] = 1
print(a)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


Задание 1.3.2

Создать 5x5 матрицу со значениями в строках от 0 до 4. Для создания
необходимо использовать функцию arrange.

In [ ]:
import numpy as np

a = np.zeros((5, 5))
a += np.arange(5)
print(a)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


Задание 1.3.3

Создать массив 3x3x3 со случайными значениями.

In [ ]:
import numpy as np

a = np.zeros((3, 3, 3))
a += np.random.rand()
print(a)

[[[0.29393523 0.29393523 0.29393523]
  [0.29393523 0.29393523 0.29393523]
  [0.29393523 0.29393523 0.29393523]]

 [[0.29393523 0.29393523 0.29393523]
  [0.29393523 0.29393523 0.29393523]
  [0.29393523 0.29393523 0.29393523]]

 [[0.29393523 0.29393523 0.29393523]
  [0.29393523 0.29393523 0.29393523]
  [0.29393523 0.29393523 0.29393523]]]


Задание 1.3.4

Создать матрицу с 0 внутри, и 1 на границах.

In [ ]:
import numpy as np

a = np.zeros((5, 5))
a[0] = 1
a[4] = 1
a[0::, 0::4] = 1
print(a)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


Задание 1.3.5

Создайте массив и отсортируйте его по убыванию.

In [ ]:
import numpy as np

a = np.arange(10)
a = np.sort(a)
a = a[::-1]
print(a)

[9 8 7 6 5 4 3 2 1 0]


Задание 1.3.6

Создайте матрицу, выведите ее форму, размер и размерность.

In [ ]:
import numpy as np

a = np.arange(16).reshape(4,4)
print(a, '\n', a.shape, '\n', a.size, '\n', a.ndim)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] 
 (4, 4) 
 16 
 2


Задание 2.3.1

Найдитн евклидово расстояние между двумя Series (точками) a и b, не
используя встроенную формулу.

In [ ]:
import pandas as pd
import numpy as np

s1 = pd.Series([2, 3])
s2 = pd.Series([3, 2])
s = np.sqrt(sum(pow(a-b, 2) for a, b in zip(s1, s2)))
print(s)

1.4142135623730951


Задание 2.3.2

Найдите в Интернете ссылку на любой csv файл и сформируйте из него
фрейм данных (например, коллекцию фреймов данных можно найти
здесь: https://github.com/akmand/datasets).

In [ ]:
import pandas as pd

url = 'atheism.csv'
dataframe = pd.read_csv(url)
print(dataframe)

           on-atheist  2005
Bulgaria      atheist  2005
Bulgaria  non-atheist  2005
Bulgaria  non-atheist  2005
Bulgaria  non-atheist  2005
Bulgaria      atheist  2005
...               ...   ...
Vietnam   non-atheist  2005
Vietnam   non-atheist  2005
Vietnam   non-atheist  2005
Vietnam   non-atheist  2005
Vietnam   non-atheist  2005

[11363 rows x 2 columns]


Задание 2.3.2

Проделайте с получившемся из предыдущего задания фреймом данных
те же действия, что и в примерах 2.2.5-2.2.7.

In [ ]:
import pandas as pd

url = 'atheism.csv'
dataframe = pd.read_csv(url)
print(dataframe.head(2))
print(dataframe.tail(3))
print(dataframe.shape)
print(dataframe.describe())
dataframe.iloc[1:4]

           on-atheist  2005
Bulgaria      atheist  2005
Bulgaria  non-atheist  2005
          on-atheist  2005
Vietnam  non-atheist  2005
Vietnam  non-atheist  2005
Vietnam  non-atheist  2005
(11363, 2)
          2005
count  11363.0
mean    2005.0
std        0.0
min     2005.0
25%     2005.0
50%     2005.0
75%     2005.0
max     2005.0


on-atheist  2005
Bulgaria  non-atheist  2005
Bulgaria  non-atheist  2005
Bulgaria  non-atheist  2005

Задание 3.3.2

Загрузить фрейм данных по ссылке:
https://raw.githubusercontent.com/akmand/datasets/master/iris.csv.
Необходимо выполнить нормализацию первого числового признака
(sepal_length_cm) с использованием минимаксного преобразования, а
второго (sepal_width_cm) с задействованием z-масштабирования.

In [ ]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler

url = 'iris.csv'
dataframe = pd.read_csv(url)
print(dataframe)

scaler = MinMaxScaler()
dataframe[['sepal_length_cm']] = scaler.fit_transform(dataframe[['sepal_length_cm']])
print(dataframe)

dataframe['sepal_width_cm'] = (dataframe['sepal_width_cm'] - dataframe['sepal_width_cm'].mean()) \
/ dataframe['sepal_width_cm'].std()


print(dataframe)

     sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm  \
0                5.1             3.5              1.4             0.2   
1                4.9             3.0              1.4             0.2   
2                4.7             3.2              1.3             0.2   
3                4.6             3.1              1.5             0.2   
4                5.0             3.6              1.4             0.2   
..               ...             ...              ...             ...   
145              6.7             3.0              5.2             2.3   
146              6.3             2.5              5.0             1.9   
147              6.5             3.0              5.2             2.0   
148              6.2             3.4              5.4             2.3   
149              5.9             3.0              5.1             1.8   

       species  
0       setosa  
1       setosa  
2       setosa  
3       setosa  
4       setosa  
..         ...  
145 